BionicUniversity\NewsBundle\Entity\Article:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        excerpt:
            type: text
        article:
            type: text
        status:
            type: integer
        author:
            type: integer
    lifecycleCallbacks: {  }
