BionicUniversity\NewsBundle\Entity\Tag:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        count:
            type: bigint
            nullable: true
    lifecycleCallbacks: {  }
    oneToMany:
        tas:
            targetEntity: BionicUniversity\NewsBundle\Entity\TagArticle
            mappedBy: tag
