bionic_university_project:
#    resource: "@BionicUniversityProjectBundle/Resources/config/routing.yml"
    resource: "@BionicUniversityProjectBundle/Controller/"
    type:     annotation
    prefix:   /projects

bionic_university_blog:
    resource: "@BionicUniversityBlogBundle/Controller/"
    type:     annotation
    prefix:   /

