bionic_university_user:
    resource: "@BionicUniversityUserBundle/Resources/config/routing.yml"
    prefix:   /

bionic_university_news:
    resource: "@BionicUniversityNewsBundle/Resources/config/routing.yml"
    prefix:   /



