bionic_university_news:
    resource: "@BionicUniversityNewsBundle/Resources/config/routing.yml"
    prefix:   /

bionic_university_student:
    resource: "@BionicUniversityStudentBundle/Resources/config/routing.yml"
    prefix:   /

