bionic_university_news_homepage:
    pattern:  /
    defaults: { _controller: BionicUniversityNewsBundle:Article:index }
BionicUniversityNewsBundle_tag:
    resource: "@BionicUniversityNewsBundle/Resources/config/routing/tag.yml"
    prefix:   /tag
BionicUniversityNewsBundle_article:
    resource: "@BionicUniversityNewsBundle/Resources/config/routing/article.yml"
    prefix:   /article
BionicUniversityNewsBundle_category:
    resource: "@BionicUniversityNewsBundle/Resources/config/routing/category.yml"
    prefix:   /category
admin_index:
    pattern:  /admin
    defaults: { _controller: "BionicUniversityNewsBundle:Admin:adminMainPage" }
