article:
    pattern:  /
    defaults: { _controller: "BionicUniversityNewsBundle:Article:index" }

article_show:
    pattern:  /{id}/show
    defaults: { _controller: "BionicUniversityNewsBundle:Article:show" }

article_new:
    pattern:  /new
    defaults: { _controller: "BionicUniversityNewsBundle:Article:new" }

article_create:
    pattern:  /create
    defaults: { _controller: "BionicUniversityNewsBundle:Article:create" }
    requirements: { _method: post }

article_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BionicUniversityNewsBundle:Article:edit" }

article_update:
    pattern:  /{id}/update
    defaults: { _controller: "BionicUniversityNewsBundle:Article:update" }
    requirements: { _method: post|put }

article_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BionicUniversityNewsBundle:Article:delete" }
    requirements: { _method: post|delete }

article_category:
    pattern:  /category/{category}
    defaults: { _controller: "BionicUniversityNewsBundle:Article:category" }

article_tag:
    pattern:  /tag/{tag}
    defaults: { _controller: "BionicUniversityNewsBundle:Article:tag" }
