parameters:
services:
    image_resizer:
        class: BionicUniversity\Bundle\BlogBundle\Resizer\ImageResizer
        arguments: [%thumb_size_height%, %thumb_size_width%]
        calls:
            - [setImageService, [@imagine, @filesystem] ]
    imagine:
        public: true
        class: Imagine\Imagick\Imagine
    transliterator:
        class: BionicUniversity\Bundle\BlogBundle\TextServices\Transliterator
        arguments: [%translit_mode%]
    reverser:
        class: BionicUniversity\Bundle\BlogBundle\TextServices\Reverse
    alias:
        class: BionicUniversity\Bundle\BlogBundle\TextServices\Aliaser
        arguments: [%alias_word_separator%]
        calls:
            - [setTransliterator, [@transliterator]]

