parameters:
services:
    image_resizer:
        class: BionicUniversity\Bundle\BlogBundle\Resizer\ImageResizer
        arguments: [%thumb_size_height%, %thumb_size_width%]
        calls:
            - [setImageService, [@imagine, @filesystem] ]
    imagine:
        public: true
        class: Imagine\Imagick\Imagine
    transliterator:
        class: BionicUniversity\Bundle\BlogBundle\TextServices\Transliterator
        arguments: [%translit_mode%]
    reverser:
        class: BionicUniversity\Bundle\BlogBundle\TextServices\Reverse
    alias:
        class: BionicUniversity\Bundle\BlogBundle\TextServices\Aliaser
        arguments: [%alias_word_separator%]
        calls:
            - [setTransliterator, [@transliterator]]
    auth_token_listener:
        class: BionicUniversity\Bundle\BlogBundle\EventListener\AuthTokenListener
        tags:
            - {name: kernel.event_listener, event: kernel.request}
#    blog_subscriber:
#        class: BionicUniversity\Bundle\BlogBundle\Subscriber\BlogSubscriber
#        tags:
#            - {name: kernel.event_subscriber}
#    post_listener:
#        class: BionicUniversity\Bundle\BlogBundle\EventListener\PostListener
#        tags:
#            - {name: doctrine.event_listener, event: prePersist, connection: default}

